export enum StatusAvaliacaoRiscoEnum {
  FINALIZADA = 0,
  APROVADA = 1,
  NEGADA = 2,
  CONDICIONADA = 3,
  NAO_PROCESSADO = 4,
  ERRO = 5,
  APROVADO_BLOQUEIO_ALCADA = 6,
  EM_PROCESSAMENTO = 9,
  NAO_SOLICITADO = 10,
  PENDENTE_APROVACAO = 11,
  BLOQUEADA = 12,
  ERRO_VALIDACAO = 98,
  ENVIADO_SEM_PROTOCOLO = 99
}
