export enum StatusSenhaCidadaoEnum {
  SENHA_ATIVA = "ATIVA",
  SENHA_NAO_CADASTRADA = "SENHA NÂO CADASTRADA",
  BLOQUEADA_POR_COMANDO = "BLOQUEADA POR COMANDO",
  BLOQUEADA_POR_EXCEDER_LIMITE_DE_TENTATIVAS = "BLOQUEADA POR EXCEDER LIMITE DE TENTATIVAS"
}
